apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maas-billing
resources:
  - configmap.yaml
  - pvc.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: maas-billing
    newName: image-registry.openshift-image-registry.svc:5000/maas-billing/maas-billing
    newTag: latest
